# Generated by Django 3.2.21 on 2023-10-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20231020_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(default='easy', max_length=255),
        ),
    ]
